POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1iZWVzb25AYmVlc29uLmNvbSIsImlkIjoxLCJpYXQiOjE3ODA4MzUyMzB9.e9PCPo4_hyxo2fWUvlEgEmSwYYdULKuKN9TQKj9CryQ

{
    "title": "On the Veg 3",
    "author": "Maverick Beeson",
    "url": "someurl.url",
    "likes": 1,
    "year": 2001
}
###
DELETE http://localhost:3001/api/blogs/1 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1iZWVzb25AYmVlc29uLmNvbSIsImlkIjoxLCJpYXQiOjE3ODA3Mzc2NTd9.1L4QwcpfkWah7N-Q66qSlpJPDP3gYCoF3fUz4EHuwnI


###
PUT http://localhost:3001/api/blogs/1 HTTP/1.1
content-type: application/json

{
    "likes": "f"
}
###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{

}
###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "On the Veg",
    "author": "Maverick Beeson",
    "likes": 500
}
###
PUT http://localhost:3001/api/blogs/3 HTTP/1.1
content-type: application/json

{
    "likes": 2000
}
###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1iZWVzb25AYmVlc29uLmNvbSIsImlkIjoxLCJpYXQiOjE3ODA3Mzc2NTd9.1L4QwcpfkWah7N-Q66qSlpJPDP3gYCoF3fUz4EHuwnI

{
    "title": "Blessed be the veg",
    "author": "John Boysen",
    "url": "someurl.url",
    "likes": 500
}