POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "mbeeson@beeson.com",
    "name": "Maverick Beeson",
    "password": "secret"
}
###
PUT http://localhost:3001/api/users/mbeeson@beeson.com HTTP/1.1
content-type: application/json

{
    "newName": "Maverick B. Beeson"
}
###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "mbeeson",
    "name": "Maverick Beeson",
    "password": "secret"
}